[project]
name = "registeration-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.13",
    "fastmcp>=2.8.1",
    "openai>=1.88.0",
    "pydantic[email]>=2.11.7",
    "streamlit>=1.46.0",
]
